version: "3.8"
services:
  frontend:
    build:
      context: ./client
      args:
        VITE_API_URI: ${VITE_API_URI}
        VITE_RAZOR_PAY_KEY: ${VITE_RAZOR_PAY_KEY}
        VITE_SUBSCRIPTION_PRICE: ${VITE_SUBSCRIPTION_PRICE}
    image: jatinsasoni/job-portal-client
    ports:
      - "80:80"
    restart: unless-stopped
  server:
    image: jatinsasoni/job-portal-server
    ports:
      - "8000:8000"
    env_file: ./server/.env
    restart: unless-stopped
